networks:
  dbnet:
services:
  phpadmin:
    container_name: php
    image: docker.io/library/phpmyadmin
    restart: unless-stopped
    networks:
      - dbnet
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db

  database: 
    container_name: db
    image: registry.redhat.io/rhel8/mariadb-105
    restart: unless-stopped
    networks:
      - dbnet
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user 
      MYSQL_PASSWORD: pass 
      MYSQL_DATABASE: Potatofacts
      MYSQL_ROOT_PASSWORD: pass
        
  backend:
    container_name: backend
    image: quay.io/dandavisredhat/potatofacts/backend:latest
    restart: unless-stopped
    networks:
      - dbnet
