#!/bin/bash

# These steps will be handled by the compose file
# in the completed project.

# Start rhel8/mariadb-105 
podman run -d --rm --name db \
-e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD=pass \
-p 3306:3306 \
-v db_data:/var/lib/mysql/data:Z \
rhel8/mariadb-105
